version: '3'
services:
  node-app:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "5054:5054"
    volumes:
     - .:/app
    environment:
      MONGO_URI: "***"
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: my-mongo-vehicles
    environment:
      MONGO_INITDB_ROOT_USERNAME: yosef050468
      MONGO_INITDB_ROOT_PASSWORD: ***
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
