version: '3'
services:
  node-app:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "5054:5054"
    volumes:
     - .:/app
    environment:
      MONGO_URI: "mongodb+srv://yosef050468:yosefha4@cluster0.qy9esls.mongodb.net/?retryWrites=true&w=majority"
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: my-mongo-vehicles
    environment:
      MONGO_INITDB_ROOT_USERNAME: yosef050468
      MONGO_INITDB_ROOT_PASSWORD: yosefha4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
