version: '3'

services:
  flask-app:
    image: auth_python-flask-app:latest 
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    container_name: host-my-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
