version: '3'

services:
  apartment_flask-app:
    image: apartment_service-apartment_flask-app:latest  # Specify the image name and version
    ports:
      - "8080:5002"  # Map host port 8080 to container port 5002
    environment:
      POSTGRES_HOST: "postgres"  # This is the service name of the PostgreSQL container
      POSTGRES_PORT: 5432        # Default PostgreSQL port
      POSTGRES_DB: "flask_db"    # Your PostgreSQL database name
      POSTGRES_USER: ${POSTGRES_USER}  # PostgreSQL username
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}  # PostgreSQL password
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    container_name: host-my-postgres
    environment:
      POSTGRES_DB: "flask_db"    # Your PostgreSQL database name
      POSTGRES_USER: ${POSTGRES_USER} # PostgreSQL username
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD} # PostgreSQL password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

volumes:
  postgres_data: {}
